### ISSUE TITLE
Not discovering Smart Plug Wi-FI (10A)

### ISSUE THREAD

**Issue by Howard3** [rgsilva/homeassistant-positivo#1]
Hello,

Thank you for your hard work on this. It seems I was able to successfully log in, however it does not seem to discover my device. I am currently running Home Assistant 2021.12.8 in a docker container on an x86 platform. I have successfully other components such as Frigate and Node Red.

The component shows up as configured within my home assistant installation after logging in however it does not seem to find any devices.

Attached is a copy of how it looks in my UI with my e-mail address redacted:
![CleanShot 2022-04-06 at 17 31 43](https://user-images.githubusercontent.com/196480/162065625-843e09cb-3685-4d8b-b629-04ad06218fff.png)

The logs don't seem to indicate much except this:
```bash
homeassistant    | 2022-04-06 20:26:19 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration positivo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
homeassistant    | 2022-04-06 20:26:40 WARNING (SyncWorker_4) [homeassistant.helpers.service] Unable to find services.yaml for the positivo integration
homeassistant    | 2022-04-06 20:26:40 WARNING (SyncWorker_1) [homeassistant.helpers.service] Unable to find services.yaml for the positivo integration
```

I am not too familiar with `services.yaml` but it is possible it's missing critical information from that file.

**Comment by rgsilva** [comment]
The `services.yaml` is missing but it still should work. The messages you are looking for are after those - they will tell you how many devices the integration found. The UI might be buggy on this part, as I really didn't put much effort on it. Ops! For standard devices I recommend you use Tuya's official integration for HA, which works pretty well and is not the result of some reverse engineering nights.

In the last updates I was way more focused on the IR part of this project, hence the high chance of no support for any other device. Feel free open a PR if you feel like coding a patch, but I really recommend you switch to Tuya's official integration for power sockets, lamps, etc.

**Comment by Howard3** [comment]
Hey,

Thanks for the quick reply and sudden realization. I had not come to the thought on just how compatible the plug is with Tuya, turns out the app is just ready to receive it as easy as the Positivo app, Tuya integration subsequently worked as expected.

Thanks again, we can close this one.
