### ISSUE TITLE
How do we use it?

### ISSUE THREAD

**Issue by Polyana-Fontes** [rgsilva/homeassistant-positivo#2]
Please, provide steps on how to install and use it, it's not clear and I have no idea on what to do with the source to run it in Home Assistant.

If it's an Home Assistant integration, maybe you can add the HACS structure to it

**Comment by rgsilva** [comment]
You have to install it manually. Unfortunately I'm not maintaining this anymore, as I've migrated the devices to ESPHome (by disassembling them and flashing the firmware). My suggestion is that you use Tuya's official integration for this instead.
